version: '3.8'
networks:
  mining-net:
    ipam:
      config:
      - subnet: 10.10.0.0/24
services:
  jdc:
    build:
      context: ./.docker/stratum
      dockerfile: Dockerfile
      target: "jdc"
    volumes:
    - ./.docker/stratum/jdc/cfg:/jdc/cfg
    ports:
    - "34265:34265"
    networks:
      mining-net:
        ipv4_address: 10.10.0.2
  template-provider:
    build:
      context: ./.docker/template-provider
      dockerfile: Dockerfile
    ports:
    - "8442:8442"
    - "18443:18443"
    volumes:
    - ./.docker/template-provider/data:/app/data
    - ./.docker/template-provider/cfg:/app/cfg
    networks:
      mining-net:
        ipv4_address: 10.10.0.3
  pool:
    build:
      context: ./.docker/stratum
      dockerfile: Dockerfile
      target: "pool"
    ports:
    - "34254:34254"
    volumes:
    - ./.docker/stratum/pool/cfg:/pool/cfg
    networks:
      mining-net:
        ipv4_address: 10.10.0.5
  btc-node:
    build:
      context: ./.docker/bitcoin-core
      dockerfile: Dockerfile
    ports:
    - "18444:18444"
    tty: true
    networks:
      mining-net:
        ipv4_address: 10.10.0.4
    #volumes:
    #- ./.docker/bitcoin.conf:/etc/bitcoin/bitcoin.conf
  jds:
    build:
      context: ./.docker/stratum
      dockerfile: Dockerfile
      target: "jds"
    volumes:
    - ./.docker/stratum/jds/cfg:/jds/cfg
    networks:
      mining-net:
        ipv4_address: 10.10.0.6
  translator-proxy:
    build:
      context: ./.docker/stratum
      dockerfile: Dockerfile
      target: "tproxy"
    volumes:
    - ./.docker/stratum/tproxy/cfg:/tproxy/cfg
    ports:
    - "34255:34255"
    networks:
      mining-net:
        ipv4_address: 10.10.0.7
  cpuminer:
    build:
      context: ./.docker/cpuminer
      dockerfile: Dockerfile
      target: "cpuminer"
    networks:
      mining-net:
        ipv4_address: 10.10.0.8
  btc-explorer:
    build:
      context: ./.docker/btc-explorer
      dockerfile: Dockerfile
      target: "btc-explorer"
    environment:
      - BTCEXP_HOST=0.0.0.0
      - BTCEXP_PORT=3002
      - BTCEXP_BITCOIND_HOST=template-provider
      - BTCEXP_BITCOIND_PORT=18443
      - BTCEXP_BITCOIND_USER=username
      - BTCEXP_BITCOIND_PASS=password
    ports:
      - "3002:3002"
    networks:
      mining-net:
        ipv4_address: 10.10.0.9